name = "abhishek-portfolio"
compatibility_date = "2024-01-15"

[build]
command = "npm run build"
publish = ".output/public"

[[redirects]]
from = "/os/*"
to = "https://os.abhishek-regrets-nothing.dev/:splat"
status = 200