name = "abhishek-portfolio"
compatibility_date = "2024-01-15"
pages_build_output_dir = "dist"

[build]
command = "npm run build"

[[redirects]]
from = "/os/*"
to = "https://os.abhishek-regrets-nothing.dev/:splat"
status = 200